resources:
  containers:
  - container: mysql
    image: mysql:5.7.24
    ports:
    - "3300:3306"
    env:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: password
  - container: postgres
    image: postgres
    ports:
    - 5432:5432
    env:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
  - container: sqlserver
    image: mcr.microsoft.com/mssql/server:2017-CU12-ubuntu
    ports:
    - "1433:1433"
    env:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd

jobs:
  - job: Linux_MySQL
    pool:
      vmimage: 'ubuntu-16.04'
    services:
      mysql: mysql
    variables:
      ConnectionString: "Server=localhost;Port=3300;User Id=test;Password=password;SSL Mode=none;Database=test;CharacterSet=utf8mb4"
    steps:
      - task: DotNetCoreInstaller@0
        displayName: 'Install DotNet Core 2.1.7'
        inputs:
          version: 2.1.503
      - task: DotNetCoreCLI@2
        displayName: MySqlConnector
        inputs:
          command: 'test'
          workingDirectory: tests/MySqlConnector.Tests
          publishTestResults: false
          arguments: '--logger "trx;LogFileName=$(Build.ArtifactStagingDirectory)/MySqlConnector.Tests.trx"'
        continueOnError: true
        env:
          ConnectionString: $(ConnectionString)
      - task: DotNetCoreCLI@2
        displayName: MySql.Data 6
        inputs:
          command: 'test'
          workingDirectory: tests/MySqlData.Tests
          publishTestResults: false
          arguments: '--logger "trx;LogFileName=$(Build.ArtifactStagingDirectory)/MySqlData.Tests.trx"'
        continueOnError: true
        env:
          ConnectionString: $(ConnectionString)
      - task: DotNetCoreCLI@2
        displayName: MySql.Data 8
        inputs:
          command: 'test'
          workingDirectory: tests/MySqlData8.Tests
          publishTestResults: false
          arguments: '--logger "trx;LogFileName=$(Build.ArtifactStagingDirectory)/MySqlData8.Tests.trx"'
        continueOnError: true
        env:
          ConnectionString: $(ConnectionString)
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: MySQL
          targetPath: $(Build.ArtifactStagingDirectory)

  - job: Linux_PostgreSQL
    pool:
      vmimage: 'ubuntu-16.04'
    services:
      postgres: postgres
    variables:
      ConnectionString: "host=localhost;user id=root;password=test;database=root"
    steps:
      - task: DotNetCoreInstaller@0
        displayName: 'Install DotNet Core 2.1.7'
        inputs:
          version: 2.1.503
      - task: DotNetCoreCLI@2
        displayName: Npgsql 3
        inputs:
          command: 'test'
          workingDirectory: tests/Npgsql3.Tests
          publishTestResults: false
          arguments: '--logger "trx;LogFileName=$(Build.ArtifactStagingDirectory)/Npgsql3.Tests.trx"'
        continueOnError: true
        env:
          ConnectionString: $(ConnectionString)
      - task: DotNetCoreCLI@2
        displayName: Npgsql 4
        inputs:
          command: 'test'
          workingDirectory: tests/Npgsql4.Tests
          publishTestResults: false
          arguments: '--logger "trx;LogFileName=$(Build.ArtifactStagingDirectory)/Npgsql4.Tests.trx"'
        continueOnError: true
        env:
          ConnectionString: $(ConnectionString)
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: PostgreSQL
          targetPath: $(Build.ArtifactStagingDirectory)

  - job: Linux_SQLite
    pool:
      vmimage: 'ubuntu-16.04'
    steps:
      - task: DotNetCoreInstaller@0
        displayName: 'Install DotNet Core 2.1.7'
        inputs:
          version: 2.1.503
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          workingDirectory: tests/MicrosoftSqlite.Tests
          publishTestResults: false
          arguments: '--logger "trx;LogFileName=$(Build.ArtifactStagingDirectory)/MicrosoftSqlite.Tests.trx"'
        continueOnError: true
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          workingDirectory: tests/MicrosoftSqlite21.Tests
          publishTestResults: false
          arguments: '--logger "trx;LogFileName=$(Build.ArtifactStagingDirectory)/MicrosoftSqlite21.Tests.trx"'
        continueOnError: true
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          workingDirectory: tests/Sqlite.Tests
          publishTestResults: false
          arguments: '--logger "trx;LogFileName=$(Build.ArtifactStagingDirectory)/Sqlite.Tests.trx"'
        continueOnError: true
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: SQLite
          targetPath: $(Build.ArtifactStagingDirectory)

  - job: Linux_SQLServer
    pool:
      vmimage: 'ubuntu-16.04'
    strategy:
      matrix:
        SqlClient:
          TEST_NAME: SqlClient.Tests
    services:
      sqlserver: sqlserver
    steps:
      - task: DotNetCoreInstaller@0
        displayName: 'Install DotNet Core 2.1.7'
        inputs:
          version: 2.1.503
      - script: |
          docker exec `docker container ls -n1 -q` /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -Q "create database sqlclient;"
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          workingDirectory: tests/$(TEST_NAME)
          publishTestResults: false
          arguments: '--logger "trx;LogFileName=$(Build.ArtifactStagingDirectory)/$(TEST_NAME).trx"'
        continueOnError: true
        env:
          ConnectionString: "data source=localhost;user id=sa;password=P@ssw0rd;initial catalog=sqlclient"
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: '$(TEST_NAME)'
          targetPath: $(Build.ArtifactStagingDirectory)

  - job: Windows
    pool:
      vmimage: 'vs2017-win2016'
    strategy:
      matrix:
        DotConnectMySql:
          TEST_NAME: DotConnectMySql.Tests
        DotConnectPostgres:
          TEST_NAME: DotConnectPostgres.Tests
        SqlClientBcl:
          TEST_NAME: SqlClientBcl.Tests
    steps:
      - task: DotNetCoreInstaller@0
        displayName: 'Install DotNet Core 2.1.7'
        inputs:
          version: 2.1.503
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          workingDirectory: tests/$(TEST_NAME)

  - job: Results
    dependsOn:
      - Linux_MySQL
      - Linux_PostgreSQL
      - Linux_SQLite
      - Linux_SQLServer
    pool:
      vmimage: 'ubuntu-16.04'
    steps:
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: MySQL
          targetPath: $(Agent.BuildDirectory)/tests
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: PostgreSQL
          targetPath: $(Agent.BuildDirectory)/tests
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: SqlClient.Tests
          targetPath: $(Agent.BuildDirectory)/tests
      - task: DownloadPipelineArtifact@0
        inputs:
          artifactName: SQLite
          targetPath: $(Agent.BuildDirectory)/tests
      - task: DotNetCoreInstaller@0
        displayName: 'Install DotNet Core 2.1.7'
        inputs:
          version: 2.1.503
      - task: DotNetCoreCLI@2
        inputs:
          command: 'run'
          workingDirectory: src/AdoNetApiTest
          publishTestResults: false
          arguments: '$(Agent.BuildDirectory)/tests $(Build.ArtifactStagingDirectory)'
      - script: 'git -c http.https://github.com.extraheader="AUTHORIZATION: basic $(GitHubAuthorization)" clone --depth 1 --branch gh-pages https://github.com/mysql-net/AdoNetResults.git ../AdoNetResults'
        displayName: Clone GitHub Pages repo
      - script: |
          cp $(Build.ArtifactStagingDirectory)/results.html index.html
          git config user.name "Build Bot"
          git config user.email "buildbot@example.com"
          git add index.html
          git commit -m "Update test results."
          git -c http.https://github.com.extraheader="AUTHORIZATION: basic $(GitHubAuthorization)" push origin
        displayName: Update GitHub Pages
        workingDirectory: ../AdoNetResults
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Results'
          targetPath: $(Build.ArtifactStagingDirectory)

trigger:
  batch: false
  branches:
    include:
    - master

# Trigger builds for PR's targeting master
pr:
  branches:
    include:
    - master
